### ISSUE TITLE
Error with lots of arguments

### ISSUE THREAD

**Issue by Killili** [aminroosta/sqlite_modern_cpp#8]
From @hanito:

Hello Again sorry for the problems, excuse me I always bring problems. Hope that they are helping lol .  Can you help me please.
I created the following table:

----------------------------------------------------------------------------------------------------------
```
CREATE TABLE IF NOT EXISTS ENTITE_CANDIDATE (ID INTEGER PRIMARY KEY NOT NULL, ID_KBP TEXT NOT NULL, wiki_title TEXT, type TEXT NOT NULL, NOM TEXT NOT NULL, CLASSE TEXT, wikiPageInLinkCountCleaned TEXT, wikiPageRank TEXT, wikiHITS TEXT, wikiPageOutLinkCountCleaned TEXT, TFIDF TEXT);"
```
------------------------------------------------------------------------------------------------------------------------------
When I want to retrieve the informations by using the following query i get the following error:
```
db << "SELECT * FROM ENTITE_CANDIDATE WHERE ID =? ;"
                         << ids.first
                         >> [& ](int id, string id_kbp, string wiki_title, string type, string name, string classe, string wikiPageInLinkCountCleaned, string wikiPageRank, string wikiHITS, string wikiPageOutLinkCountCleaned, string tfidf)
                      {
                          cout <<" ==> " << tfidf << endl;
                      };
```

```
||=== Build: Debug in entityLinking (compiler: GNU GCC Compiler) ===|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h||In instantiation of ‘sqlite::database_binder::operator>>(FUNC) [with FUNC = LinkEntities::link()::__lambda9]::__lambda6’:|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h|215|required from ‘struct sqlite::database_binder::operator>>(FUNC) [with FUNC = LinkEntities::link()::__lambda9]::__lambda6’|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h|214|required from ‘void sqlite::database_binder::operator>>(FUNC) [with FUNC = LinkEntities::link()::__lambda9]’|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/LinkEntities.cpp|86|required from here|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h|38|error: ‘static void sqlite::binder<N>::run(sqlite::database_binder&, F) [with F = LinkEntities::link()::__lambda9; int N = 11]’ is private|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h|215|error: within this context|
/home/hani/Documents/articles/Architecture/Modules/entityLinking/3rdparty/sqlite_modern_cpp.h|38|error: ‘static void sqlite::binder<N>::run(sqlite::database_binder&, F) [with F = LinkEntities::link()::__lambda9; int N = 11]’, declared using local type ‘LinkEntities::link()::__lambda9’, is used but never defined [-fpermissive]|
/usr/include/c++/4.8/functional|2443|error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = sqlite::database_binder::operator>>(FUNC) [with FUNC = LinkEntities::link()::__lambda9]::__lambda6; <template-parameter-2-2> = void; _Res = void; _ArgTypes = {}]’, declared using local type ‘sqlite::database_binder::operator>>(FUNC) [with FUNC = LinkEntities::link()::__lambda9]::__lambda6’, is used but never defined [-fpermissive]|
||=== Build failed: 4 error(s), 4 warning(s) (0 minute(s), 3 second(s)) ===|
```

**Comment by Killili** [comment]
I can confirm that issue, with the version before @KnairdA changes its imposible because there are 11 arguments and only 10 binders for arguments.
With the current Version its a bit trickyer:

../src/utility/sfinae.h(9): error C2039: 'type' : is not a member of 'std::enable_if<false,size_t>'

No idea what that is so could someone plz do some template magic here ;)

**Comment by KnairdA** [comment]
@hanito example compiles on my system using _GCC 4.9.2 20150304_. So the problem seems to be the compiler version being to old. Are you using the current version of the library?

@Killili which compiler version are you using? Does it work if you revert b022565a403aee04768f82f78a8687a3362ca559?

**Comment by Killili** [comment]
The VCC in VS2013 Update 4 (cant use the PC right now so i'm not sure)

**Comment by Killili** [comment]
Reading about that error did not help but what i found boils down to the compiler not being able to follow the false route of that template.

If i checkout b022565a403aee04768f82f78a8687a3362ca559 i have partly merged files with conflicts, dont know whats wrong there.

**Comment by hanito** [comment]
@aminroosta I didn't download the new version of the library. I'll download the update version of the library. I'll also download GCC 4.9. I'll let you know how it works.

**Comment by KnairdA** [comment]
I have extracted the specific part I suggested to revert in the following patch:

```patch
diff --git src/sqlite_modern_cpp.h src/sqlite_modern_cpp.h
index d051aab..b6c01b5 100644
--- src/sqlite_modern_cpp.h
+++ src/sqlite_modern_cpp.h
@@ -280,10 +280,9 @@ private:
 public:
 	template<
 		typename    Function,
-		typename... Values,
-		utility::enable_if<(sizeof...(Values) < Count)> = 0
+		typename... Values
 	>
-	static void run(
+	static typename std::enable_if<(sizeof...(Values) < Count), void>::type run(
 		database_binder& db,
 		Function&        function,
 		Values&&...      values
@@ -296,10 +295,9 @@ public:
 
 	template<
 		typename    Function,
-		typename... Values,
-		utility::enable_if<(sizeof...(Values) == Count)> = 0
+		typename... Values
 	>
-	static void run(
+	static typename std::enable_if<(sizeof...(Values) == Count), void>::type run(
 		database_binder&,
 		Function&        function,
 		Values&&...      values
```

It should apply cleanly to the current _head_. My suspicion is that the fancy way in which `std::enable_if` is moved to the template arguments by b022565 causes the problems.

**Comment by Killili** [comment]
Ok, that patch did not apply ... so i did it by hand (probably a Windows issue). But it did not change the problem.
```
1>  ConsoleApplication1.cpp
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): error C2039: 'type' : is not a member of 'std::enable_if<false,void>'
1>          c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(223) : see reference to class template instantiation 'sqlite::binder<1>' being compiled
1>          c:\users\------\documents\visual studio 2013\projects\consoleapplication1\consoleapplication1\consoleapplication1.cpp(53) : see reference to function template instantiation 'void sqlite::database_binder::operator >><Test::initialize::<lambda_9b13f18e5e2b4e689d9ec80ab0e7ed31>,0>(Function)' being compiled
1>          with
1>          [
1>              Function=Test::initialize::<lambda_9b13f18e5e2b4e689d9ec80ab0e7ed31>
1>          ]
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): error C2146: syntax error : missing ';' before identifier 'run'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): error C2238: unexpected token(s) preceding ';'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): error C2143: syntax error : missing ';' before '<end Parse>'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): warning C4183: 'run': missing return type; assumed to be a member function returning 'int'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(304): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C2039: 'type' : is not a member of 'std::enable_if<false,void>'
1>          c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(223) : see reference to class template instantiation 'sqlite::binder<2>' being compiled
1>          c:\users\-------\documents\visual studio 2013\projects\consoleapplication1\consoleapplication1\consoleapplication1.cpp(108) : see reference to function template instantiation 'void sqlite::database_binder::operator >><Sub::initialize::<lambda_796d9df2356eb1ee8dc891d176904c39>,0>(Function)' being compiled
1>          with
1>          [
1>              Function=Sub::initialize::<lambda_796d9df2356eb1ee8dc891d176904c39>
1>          ]
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C2146: syntax error : missing ';' before identifier 'run'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C2238: unexpected token(s) preceding ';'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C2686: cannot overload static and non-static member functions with the same parameter types
1>          c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(285): could be 'void sqlite::binder<2>::run(sqlite::database_binder &,Function &,Values &&...)'
1>          c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): or       'int sqlite::binder<2>::run(sqlite::database_binder &,Function &,Values &&...)'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): error C2143: syntax error : missing ';' before '<end Parse>'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(300): warning C4183: 'run': missing return type; assumed to be a member function returning 'int'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(307): error C2143: syntax error : missing ';' before '}'
1>c:\libs\sqlite_modern_cpp\src\sqlite_modern_cpp.h(307): error C2238: unexpected token(s) preceding ';'
```

**Comment by KnairdA** [comment]
Hm… As I do not have access to a Visual Studio instance right now could you try this version?

```patch
diff --git src/sqlite_modern_cpp.h src/sqlite_modern_cpp.h
index d051aab..b300de5 100644
--- src/sqlite_modern_cpp.h
+++ src/sqlite_modern_cpp.h
@@ -281,9 +281,9 @@ public:
 	template<
 		typename    Function,
 		typename... Values,
-		utility::enable_if<(sizeof...(Values) < Count)> = 0
+		std::size_t Helper = Count
 	>
-	static void run(
+	static typename std::enable_if<(sizeof...(Values) < Helper), void>::type run(
 		database_binder& db,
 		Function&        function,
 		Values&&...      values
@@ -297,9 +297,9 @@ public:
 	template<
 		typename    Function,
 		typename... Values,
-		utility::enable_if<(sizeof...(Values) == Count)> = 0
+		std::size_t Helper = Count
 	>
-	static void run(
+	static typename std::enable_if<(sizeof...(Values) == Helper), void>::type run(
 		database_binder&,
 		Function&        function,
 		Values&&...      values
```
This issue is quite weird as the patched version without the helper template argument should not even compile if my interpretation of the standard is correct. One way or the other the version in this comment should work. If it doesn't… I either don't know or there is something entirely different going on.

**Comment by aminroosta** [comment]
current repository didn't work even with visual studio 2015 ctp6.
@KnairdA this patch works under visual studio 2015 ctp6...
I have only vs 2015 ctp ... but i think that this patch should work under visual studio 2013.


@KnairdA can you give a link explaining all that **enable_if** and **sfinae** stuff ... i want to start learning those new topics **tnx** :)

@hanito this patch should work with the current version of repository ...
i recommend that you upgrade to this version ...  
if you still have problems (even with this patch) you can use the old version and
reduce the number of fields in the table ( <= 10) ...
when you have more than 7 or 8 fields in a database table
there is clearly a design problem in you database (but that's another matter).

**Comment by Killili** [comment]
The last patch did the trick for me, too. 
So we should checkin that Version.

**Comment by KnairdA** [comment]
Very good - I just checked in a corresponding fix. While this issue did not apply to the merging of the _extraction operator overloads_ I also changed them back to plan `std::enable_if` return types to preserve consistency.

**Comment by aminroosta** [comment]
@KnairdA  **thanks**.
